### ISSUE TITLE
[G5k] Some clusters do not expose the `mountable` NIC information in the API.

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enoslib#15]
The [`get_cluster_interfaces`](https://github.com/BeyondTheClouds/enoslib/blob/master/enoslib/infra/enos_g5k/utils.py#L125) seeks for mountable NICs by querying the API. But some NICs do not expose the mountable information.

Example with ecotype/nantes and NIC `bmc`.
```
curl -k -X GET https://api.grid5000.fr/stable/grid5000/sites/nantes/clusters/ecotype/nodes | jq '.items[0].network_adapters'
```

It is better to use `dict.get("mountable", False)`.

**Comment by msimonin** [comment]
Is it a bug on g5k side ? Or should we handle both cases ?

**Comment by rcherrueau** [comment]
It works if you change [line 125](https://github.com/BeyondTheClouds/enoslib/blob/master/enoslib/infra/enos_g5k/utils.py#L125) by `if nic.get('mountable', False)`. However, I don't know if it is a G5k bug or not.

@badock Is it a bug from your side? If you do the following REST request, that list all network interfaces on ecotype, then "bmc" does not show the `mountable` option.

```
curl -k -X GET https://api.grid5000.fr/stable/grid5000/sites/nantes/clusters/ecotype/nodes|\
   jq '.items[0].network_adapters'
```

**Comment by msimonin** [comment]
@rcherrueau in any case you are right, using `get` is better.
