### ISSUE TITLE
Host instancies can't be safely loaded

### ISSUE THREAD

**Issue by quentinLeDilavrec** [BeyondTheClouds/enoslib#40]
Host as it is now
https://github.com/BeyondTheClouds/enoslib/blob/7f1b9faea59c7b1c87289fcd8ebbdf34e43c1cc8/enoslib/host.py#L4
An example of a class that can be safely loaded after a dump
from https://pyyaml.org/wiki/PyYAMLDocumentation#LoadingYAML
``` python
class Monster(yaml.YAMLObject):
    yaml_tag = u'!Monster'
    def __init__(self, name, hp, ac, attacks):
         self.name = name
         self.hp = hp
         self.ac = ac
         self.attacks = attacks
     def __repr__(self):
         return "%s(name=%r, hp=%r, ac=%r, attacks=%r)" % (
             self.__class__.__name__, self.name, self.hp, self.ac, self.attacks)
```
A more complicated solution, but avoid inheriting from YAMLObject,
is to make a "representer" and a "constructor" like it's described in the article after the previous example.
Those two are made by PyYaml in case of inheriting of YAMLObject

Anyway depending on the content of Host.extra the object might not be loaded safely,
but the user will be able to do the same to his python objects if he wants to safe_load

**Comment by msimonin** [comment]
But at the end you still need to import the `Host` definition from `enoslib.host` if you want to read the env from a third party python program ? Am I wrong ?

**Comment by quentinLeDilavrec** [comment]
```Host``` isn't really needed, but even if enoslib was required, allowing safe_load is better.

In practice, safe loading a tagged yaml object only need ```yaml.add_constructor(u'!dice', dice_constructor)``` and the constructor function, (as shown in the previous link) to load.
A few lines compared to loading all enoslib and it's dependancies.
It's the safe and elegant way to do it. Because in the end I don't even need all the attributes of ```Host```
