### ISSUE TITLE
make run_ansible's on_error_continue option finer grained

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enoslib#66]
We could do 
```
run_ansible(...,....,on_errors_continue=['machine01', 'machine02'])
```
In this case if ansible fails machine01 or machine02 it will not raise any Exception.

Use case: in enos if one compute (over many) fails that's not a big deal

**Comment by jrbalderrama** [comment]
The filter to continue on errors should be machine-based or role-based?

**Comment by msimonin** [comment]
Until #68 isn't finished, we'll need to use the machines.

After that we could actually pass both roles and machines
