### ISSUE TITLE
Hardcoded IP may prevent VMs deployed on G5K to have a correct DNS configuration

### ISSUE THREAD

**Issue by badock** [BeyondTheClouds/enoslib#84]
Hello,

we are experiencing an issue with the Grid'5000 jenkins test dedicated to Enos : the OpenStack deployment works well, a project and a VM are created, however at the end of the deployment we test if the VM can install debian packages. At this moment, the test fails and we noticed that the VM could not resolve the URL of the debian mirror:

```
Err:1 http://security.debian.org stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
```

We noticed the following line:
https://github.com/BeyondTheClouds/enoslib/blob/5ae5cac64b4f947fd21e4facc23aa329eb9cf17d/enoslib/infra/enos_g5k/provider.py#L51

It seems that ```131.254.203.235``` correspond to a DNS (```dns-g5k.irisa.fr```), and that a VM configured with enos' G5K provider will inherit this setting, and thus will use ```131.254.203.235``` as a DNS server. However, resolving debian.org seems broken with ```131.254.203.235```:

```
dig @131.254.203.235 debian.org

; <<>> DiG 9.10.3-P4-Debian <<>> @131.254.203.235 debian.org
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

On the other hand we recently changed the Grid'5000 DNS server, but kept the same domain name ```dns.grid5000.fr```. Via this DNS server, ```debian.org``` can be resolved:

```
dig @dns.grid5000.fr debian.org

; <<>> DiG 9.10.3-P4-Debian <<>> @dns.grid5000.fr debian.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7224
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;debian.org.			IN	A

;; ANSWER SECTION:
debian.org.		300	IN	A	5.153.231.4
debian.org.		300	IN	A	128.31.0.62
debian.org.		300	IN	A	130.89.148.14
debian.org.		300	IN	A	149.20.4.15

;; Query time: 47 msec
;; SERVER: 172.16.207.101#53(172.16.207.101)
;; WHEN: Tue Dec 11 13:49:35 CET 2018
;; MSG SIZE  rcvd: 103
```
Would it be possible that the G5K provider leverages ```dns.grid5000.fr``` instead of ``` 131.254.203.235```?

Best Regards,

Jonathan

**Comment by msimonin** [comment]
@badock I've proposed a patch. Could you have a look ?
